// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;

namespace SDK.Platform.AliExpressApi.RModel
{
    public class SkuType
    {
        public int order;
        public int pId;
        public string pName;
        public string pValue;
        public int pValueId;
        public string selfDefineValue;
        public string showType;
        public string skuImg;
        public int skuImgVersion;
    }

    public class SkuListType
    {
        public SkuType[] sku;
    }

    ///// <summary>
    ///// 货币
    ///// </summary>
    //public class Currency
    //{
    //    /// <summary>
    //    /// 小数位数
    //    /// </summary>
    //    [JsonProperty("defaultFractionDigits")]
    //    public int DefaultFractionDigits { get; set; }
    //    /// <summary>
    //    /// 货币代码
    //    /// </summary>
    //    [JsonProperty("currencyCode")]
    //    public string CurrencyCode { get; set; }
    //    /// <summary>
    //    /// 货币符号
    //    /// </summary>
    //    [JsonProperty("symbol")]
    //    public string Symbol { get; set; }
    //}
    ///// <summary>
    ///// 金额
    ///// </summary>
    //public class PayAmount
    //{
    //    /// <summary>
    //    /// 总计金额
    //    /// </summary>
    //    [JsonProperty("amount")]
    //    public decimal Amount { get; set; }

    //    [JsonProperty("cent")]
    //    public int Cent { get; set; }

    //    [JsonProperty("currencyCode")]
    //    public string CurrencyCode { get; set; }
    //    /// <summary>
    //    /// 分的定义，1块除100
    //    /// </summary>
    //    [JsonProperty("centFactor")]
    //    public int CentFactor { get; set; }
    //    /// <summary>
    //    /// 货币
    //    /// </summary>
    //    [JsonProperty("currency")]
    //    public Currency Currency { get; set; }
    //    public override string ToString()
    //    {
    //        return this.Amount + " " + this.CurrencyCode; ;
    //    }
    //}

    ///// <summary>
    ///// 订单产品
    ///// </summary>
    //public class ProductList
    //{
    //    /// <summary>
    //    /// 子订单ID
    //    /// </summary>
    //    [JsonProperty("childId")]
    //    public string ChildId { get; set; }
    //    /// <summary>
    //    /// 备货时间
    //    /// </summary>
    //    [JsonProperty("goodsPrepareTime")]
    //    public int GoodsPrepareTime { get; set; }
    //    /// <summary>
    //    /// 物流金额
    //    /// </summary>
    //    [JsonProperty("logisticsAmount")]
    //    public PayAmount LogisticsAmount { get; set; }
    //    /// <summary>
    //    /// 订单备注
    //    /// </summary>
    //    [JsonProperty("memo")]
    //    public string Memo { get; set; }
    //    /// <summary>
    //    /// 卖家FirstName
    //    /// </summary>
    //    [JsonProperty("sellerSignerFirstName")]
    //    public string SellerSignerFirstName { get; set; }
    //    /// <summary>
    //    /// 总产品数量
    //    /// </summary>
    //    [JsonProperty("totalProductAmount")]
    //    public PayAmount TotalProductAmount { get; set; }
    //    /// <summary>
    //    /// 限时达
    //    /// </summary>
    //    [JsonProperty("freightCommitDay")]
    //    public string FreightCommitDay { get; set; }

    //    [JsonProperty("canSubmitIssue")]
    //    public bool CanSubmitIssue { get; set; }
    //    /// <summary>
    //    /// 产品单位
    //    /// </summary>
    //    [JsonProperty("productUnit")]
    //    public string ProductUnit { get; set; }
    //    /// <summary>
    //    /// 物流类型
    //    /// </summary>
    //    [JsonProperty("logisticsType")]
    //    public string LogisticsType { get; set; }

    //    [JsonProperty("issueStatus")]
    //    public string IssueStatus { get; set; }
    //    /// <summary>
    //    /// 订单号
    //    /// </summary>
    //    [JsonProperty("orderId")]
    //    public string OrderId { get; set; }
    //    /// <summary>
    //    /// 物流服务
    //    /// </summary>
    //    [JsonProperty("logisticsServiceName")]
    //    public string LogisticsServiceName { get; set; }
    //    /// <summary>
    //    /// 子订单状态
    //    /// </summary>
    //    [JsonProperty("sonOrderStatus")]
    //    public string SonOrderStatus { get; set; }
    //    /// <summary>
    //    /// 产品镜像链接
    //    /// </summary>
    //    [JsonProperty("productSnapUrl")]
    //    public string ProductSnapUrl { get; set; }
    //    /// <summary>
    //    /// 假一赔三
    //    /// </summary>
    //    [JsonProperty("moneyBack3x")]
    //    public bool MoneyBack3x { get; set; }

    //    [JsonProperty("skuCode")]
    //    public string SkuCode { get; set; }
    //    /// <summary>
    //    /// 产品ID
    //    /// </summary>
    //    [JsonProperty("productId")]
    //    public string ProductId { get; set; }

    //    [JsonProperty("productCount")]
    //    public int ProductCount { get; set; }
    //    /// <summary>
    //    /// 妥投时间
    //    /// </summary>
    //    [JsonProperty("deliveryTime")]
    //    public string DeliveryTime { get; set; }
    //    /// <summary>
    //    /// 产品单位价格
    //    /// </summary>
    //    [JsonProperty("productUnitPrice")]
    //    public PayAmount ProductUnitPrice { get; set; }
    //    /// <summary>
    //    /// 产品单位货币
    //    /// </summary>
    //    [JsonProperty("productUnitPriceCur")]
    //    public PayAmount ProductUnitPriceCur { get; set; }
    //    /// <summary>
    //    /// 卖家LastName
    //    /// </summary>
    //    [JsonProperty("sellerSignerLastName")]
    //    public string SellerSignerLastName { get; set; }
    //    /// <summary>
    //    /// 产品图片链接
    //    /// </summary>
    //    [JsonProperty("productImgUrl")]
    //    public string ProductImgUrl { get; set; }

    //    [JsonProperty("showStatus")]
    //    public string ShowStatus { get; set; }
    //    /// <summary>
    //    /// 产品名称
    //    /// </summary>
    //    [JsonProperty("productName")]
    //    public string ProductName { get; set; }
    //    /// <summary>
    //    /// 发货时间
    //    /// </summary>
    //    [JsonProperty("sendGoodsTime")]
    //    public System.DateTimeOffset? SendGoodsTime { get; set; }
    //}

    ///// <summary>
    ///// 订单列表
    ///// </summary>
    //public class OrderList
    //{
    //    /// <summary>
    //    /// 子产品列表
    //    /// </summary>
    //    [JsonProperty("productList")]
    //    public ProductList[] ProductList { get; set; }
    //    /// <summary>
    //    /// 冻结状态
    //    /// </summary>
    //    [JsonProperty("frozenStatus")]
    //    public string FrozenStatus { get; set; }
    //    /// <summary>
    //    /// 纠纷状态
    //    /// </summary>
    //    [JsonProperty("issueStatus")]
    //    public string IssueStatus { get; set; }
    //    /// <summary>
    //    /// 买家登录ID
    //    /// </summary>
    //    [JsonProperty("buyerLoginId")]
    //    public string BuyerLoginId { get; set; }
    //    /// <summary>
    //    /// 卖家名称 
    //    /// </summary>
    //    [JsonProperty("sellerSignerFullname")]
    //    public string SellerSignerFullname { get; set; }

    //    [JsonProperty("hasRequestLoan")]
    //    public bool HasRequestLoan { get; set; }
    //    /// <summary>
    //    /// 订单编号
    //    /// </summary>
    //    [JsonProperty("orderId")]
    //    public long OrderId { get; set; }
    //    /// <summary>
    //    /// 支付金额
    //    /// </summary>
    //    [JsonProperty("payAmount")]
    //    public PayAmount PayAmount { get; set; }
    //    /// <summary>
    //    /// 订单创建时间
    //    /// </summary>
    //    [JsonProperty("gmtCreate")]
    //    public System.DateTimeOffset? GmtCreate { get; set; }
    //    /// <summary>
    //    /// 最后修改时间
    //    /// </summary>
    //    [JsonProperty("gmtModified")]
    //    public System.DateTimeOffset? GmtModified { get; set; }
    //    /// <summary>
    //    /// 支付类型
    //    /// </summary>
    //    [JsonProperty("paymentType")]
    //    public string PaymentType { get; set; }
    //    /// <summary>
    //    /// 备注
    //    /// </summary>
    //    [JsonProperty("memo")]
    //    public string Memo { get; set; }
    //    /// <summary>
    //    /// 订单状态 PLACE_ORDER_SUCCESS:等待买家付款; IN_CANCEL:买家申请取消; WAIT_SELLER_SEND_GOODS:等待您发货; SELLER_PART_SEND_GOODS:部分发货; WAIT_BUYER_ACCEPT_GOODS:等待买家收货; FUND_PROCESSING:买家确认收货后，等待退放款处理的状态; FINISH:已结束的订单; IN_ISSUE:含纠纷的订单; IN_FROZEN:冻结中的订单; WAIT_SELLER_EXAMINE_MONEY:等待您确认金额; RISK_CONTROL:订单处于风控24小时中，从买家在线支付完成后开始，持续24小时。
    //    /// </summary>
    //    [JsonProperty("orderStatus")]
    //    public string OrderStatus { get; set; }
    //    /// <summary>
    //    /// 买家全名 
    //    /// </summary>
    //    [JsonProperty("buyerSignerFullname")]
    //    public string BuyerSignerFullname { get; set; }
    //    /// <summary>
    //    /// 支付时间（和订单详情中gmtPaysuccess字段意义相同。)
    //    /// </summary>
    //    [JsonProperty("gmtPayTime")]
    //    public System.DateTimeOffset? GmtPayTime { get; set; }

    //    /// <summary>
    //    /// 超时剩余时间
    //    /// </summary>
    //    [JsonProperty("timeoutLeftTime")]
    //    public System.TimeSpan? TimeoutLeftTime { get { return _timeoutLeftTime; } set { _timeoutLeftTime = value.HasValue ? new System.TimeSpan(value.Value.Ticks * 10000) : new Nullable<System.TimeSpan>(); } }
    //    private System.TimeSpan? _timeoutLeftTime = null;
    //    /// <summary>
    //    /// 付款状态
    //    /// </summary>
    //    [JsonProperty("fundStatus")]
    //    public string FundStatus { get; set; }
    //    /// <summary>
    //    /// 订单类型（ae_commonAE普通订单、SAFEPAY 批发或者sourcing小单 、QC 验货 、SC_SHIP 海运 ）
    //    /// </summary>
    //    [JsonProperty("bizType")]
    //    public string BizType { get; set; }
    //    /// <summary>
    //    /// 发货时间
    //    /// </summary>
    //    [JsonProperty("gmtSendGoodsTime")]
    //    public System.DateTimeOffset? GmtSendGoodsTime { get; set; }
    //    /// <summary>
    //    /// 剩余发货时间（天）
    //    /// </summary>
    //    [JsonProperty("leftSendGoodDay")]
    //    public string LeftSendGoodDay { get; set; }
    //    /// <summary>
    //    /// 剩余发货时间（小时）
    //    /// </summary>
    //    [JsonProperty("leftSendGoodHour")]
    //    public string LeftSendGoodHour { get; set; }
    //    /// <summary>
    //    /// 剩余发货时间（分钟）
    //    /// </summary>
    //    [JsonProperty("leftSendGoodMin")]
    //    public string LeftSendGoodMin { get; set; }
    //    /// <summary>
    //    /// 总金额
    //    /// </summary>
    //    [JsonProperty("amountTotal")]
    //    public AmountTotal AmountTotal { get; set; }
    //    /// <summary>
    //    ///子订单列表
    //    /// </summary>
    //    [JsonProperty("sonOrderList")]
    //    public SonOrderList[] SonOrderList { get; set; }
    //}
    ///// <summary>
    ///// 总金额
    ///// </summary>
    //public class AmountTotal
    //{
    //    /// <summary>
    //    /// 总金额
    //    /// </summary>
    //    [JsonProperty("amount")]
    //    public double Amount { get; set; }

    //    [JsonProperty("cent")]
    //    public int Cent { get; set; }
    //    /// <summary>
    //    /// 货币代码
    //    /// </summary>
    //    [JsonProperty("currencyCode")]
    //    public string CurrencyCode { get; set; }

    //    [JsonProperty("centFactor")]
    //    public int CentFactor { get; set; }
    //    /// <summary>
    //    /// 货币
    //    /// </summary>
    //    [JsonProperty("currency")]
    //    public Currency Currency { get; set; }
    //}
    ///// <summary>
    ///// 返回的订单列表
    ///// </summary>
    //public class AliOrderListType : AliErrorType
    //{
    //    /// <summary>
    //    /// 订单总数
    //    /// </summary>
    //    [JsonProperty("totalItem")]
    //    public int TotalItem { get; set; }
    //    /// <summary>
    //    /// 订单列表
    //    /// </summary>
    //    [JsonProperty("orderList")]
    //    public OrderList[] OrderList { get; set; }
    //}

    //public class ReceiptAddress
    //{
    //    /// <summary>
    //    /// 邮编
    //    /// </summary>
    //    [JsonProperty("zip")]
    //    public string Zip { get; set; }
    //    /// <summary>
    //    /// 地址2
    //    /// </summary>
    //    [JsonProperty("address2")]
    //    public string Address2 { get; set; }
    //    /// <summary>
    //    /// 详细地址
    //    /// </summary>
    //    [JsonProperty("detailAddress")]
    //    public string DetailAddress { get; set; }
    //    /// <summary>
    //    /// 国家
    //    /// </summary>
    //    [JsonProperty("country")]
    //    public string Country { get; set; }
    //    /// <summary>
    //    /// 城市
    //    /// </summary>
    //    [JsonProperty("city")]
    //    public string City { get; set; }
    //    /// <summary>
    //    /// 移动电话
    //    /// </summary>
    //    [JsonProperty("phoneNumber")]
    //    public string PhoneNumber { get; set; }
    //    /// <summary>
    //    /// 省州
    //    /// </summary>
    //    [JsonProperty("province")]
    //    public string Province { get; set; }
    //    /// <summary>
    //    /// 电话区域编码
    //    /// </summary>
    //    [JsonProperty("phoneArea")]
    //    public string PhoneArea { get; set; }
    //    /// <summary>
    //    /// 电话国家编码
    //    /// </summary>
    //    [JsonProperty("phoneCountry")]
    //    public string PhoneCountry { get; set; }
    //    /// <summary>
    //    /// 收件人全名 
    //    /// </summary>
    //    [JsonProperty("contactPerson")]
    //    public string ContactPerson { get; set; }
    //    /// <summary>
    //    /// 移动电话
    //    /// </summary>
    //    [JsonProperty("mobileNo")]
    //    public string MobileNo { get; set; }
    //    public override string ToString()
    //    {
    //        return string.Join(",", this.ContactPerson, this.DetailAddress, this.City, this.Province, this.Zip, this.Country);
    //    }
    //}
    ///// <summary>
    ///// 买家信息
    ///// </summary>
    //public class BuyerInfo
    //{

    //    [JsonProperty("lastName")]
    //    public string LastName { get; set; }

    //    [JsonProperty("loginId")]
    //    public string LoginId { get; set; }

    //    [JsonProperty("email")]
    //    public string Email { get; set; }

    //    [JsonProperty("firstName")]
    //    public string FirstName { get; set; }

    //    [JsonProperty("country")]
    //    public string Country { get; set; }
    //}

    ///// <summary>
    ///// 子订单产品信息
    ///// </summary>
    //public class ChildOrderExtInfoList
    //{

    //    [JsonProperty("unitPrice")]
    //    public PayAmount UnitPrice { get; set; }

    //    [JsonProperty("quantity")]
    //    public int Quantity { get; set; }

    //    [JsonProperty("sku")]
    //    public string Sku { get; set; }

    //    [JsonProperty("productName")]
    //    public string ProductName { get; set; }

    //    [JsonProperty("productId")]
    //    public string ProductId { get; set; }
    //}
    ///// <summary>
    ///// 纠纷信息
    ///// </summary>
    //public class IssueInfo
    //{

    //    [JsonProperty("issueStatus")]
    //    public string IssueStatus { get; set; }
    //}





    //public class ChildOrderList
    //{

    //    [JsonProperty("lotNum")]
    //    public int LotNum { get; set; }

    //    [JsonProperty("productAttributes")]
    //    public string ProductAttributes { get; set; }
    //    /// <summary>
    //    /// 订单状态
    //    /// </summary>
    //    [JsonProperty("orderStatus")]
    //    public string OrderStatus { get; set; }
    //    /// <summary>
    //    /// 产品单位
    //    /// </summary>
    //    [JsonProperty("productUnit")]
    //    public string ProductUnit { get; set; }

    //    [JsonProperty("skuCode")]
    //    public string SkuCode { get; set; }

    //    [JsonProperty("productId")]
    //    public string ProductId { get; set; }

    //    [JsonProperty("id")]
    //    public string Id { get; set; }
    //    /// <summary>
    //    /// 冻结状态
    //    /// </summary>
    //    [JsonProperty("frozenStatus")]
    //    public string FrozenStatus { get; set; }
    //    /// <summary>
    //    /// 纠纷状态
    //    /// </summary>
    //    [JsonProperty("issueStatus")]
    //    public string IssueStatus { get; set; }
    //    /// <summary>
    //    /// 产品数量
    //    /// </summary>
    //    [JsonProperty("productCount")]
    //    public int ProductCount { get; set; }

    //    [JsonProperty("fundStatus")]
    //    public string FundStatus { get; set; }

    //    [JsonProperty("initOrderAmt")]
    //    public PayAmount InitOrderAmt { get; set; }

    //    [JsonProperty("productName")]
    //    public string ProductName { get; set; }

    //    [JsonProperty("productPrice")]
    //    public PayAmount ProductPrice { get; set; }
    //}


    ///// <summary>
    ///// 返回的交易订单详情
    ///// </summary>
    //public class AliOrderType : AliErrorType
    //{
    //    /// <summary>
    //    /// 收货地址 
    //    /// </summary>
    //    [JsonProperty("receiptAddress")]
    //    public ReceiptAddress ReceiptAddress { get; set; }

    //    [JsonProperty("gmtModified")]
    //    public System.DateTimeOffset? GmtModified { get; set; }
    //    /// <summary>
    //    /// 买家信息 
    //    /// </summary>
    //    [JsonProperty("buyerInfo")]
    //    public BuyerInfo BuyerInfo { get; set; }
    //    /// <summary>
    //    /// 买家登录ID 
    //    /// </summary>
    //    [JsonProperty("buyerloginid")]
    //    public string BuyerloginId { get; set; }

    //    [JsonProperty("logisticsAmount")]
    //    public PayAmount LogisticsAmount { get; set; }
    //    /// <summary>
    //    /// 子订单产品信息
    //    /// </summary>
    //    [JsonProperty("childOrderExtInfoList")]
    //    public ChildOrderExtInfoList[] ChildOrderExtInfoList { get; set; }
    //    /// <summary>
    //    /// 留言信息 
    //    /// </summary>
    //    [JsonProperty("orderMsgList")]
    //    public object[] OrderMsgList { get; set; }
    //    /// <summary>
    //    /// 纠纷信息 
    //    /// </summary>
    //    [JsonProperty("issueInfo")]
    //    public IssueInfo IssueInfo { get; set; }
    //    /// <summary>
    //    /// 物流信息
    //    /// </summary>
    //    [JsonProperty("logisticInfoList")]
    //    public LogisticInfoList[] LogisticInfoList { get; set; }

    //    //[JsonProperty("id")]
    //    //public string Id { get; set; }
    //    /// <summary>
    //    /// 纠纷状态
    //    /// </summary>
    //    [JsonProperty("issueStatus")]
    //    public string IssueStatus { get; set; }

    //    [JsonProperty("frozenStatus")]
    //    public string FrozenStatus { get; set; }
    //    /// <summary>
    //    /// 物流状态
    //    /// </summary>
    //    [JsonProperty("logisticsStatus")]
    //    public string LogisticsStatus { get; set; }

    //    [JsonProperty("orderAmount")]
    //    public PayAmount OrderAmount { get; set; }
    //    /// <summary>
    //    /// 卖家全名
    //    /// </summary>
    //    [JsonProperty("sellerSignerFullname")]
    //    public string SellerSignerFullname { get; set; }

    //    [JsonProperty("initOderAmount")]
    //    public PayAmount InitOderAmount { get; set; }
    //    /// <summary>
    //    /// 子订单信息 
    //    /// </summary>
    //    [JsonProperty("childOrderList")]
    //    public ChildOrderList[] ChildOrderList { get; set; }

    //    [JsonProperty("gmtCreate")]
    //    public System.DateTimeOffset? GmtCreate { get; set; }
    //    /// <summary>
    //    /// 卖家id
    //    /// </summary>
    //    [JsonProperty("sellerOperatorLoginId")]
    //    public string SellerOperatorLoginId { get; set; }
    //    /// <summary>
    //    /// 放款信息("loan_none"无放款；"wait_loan"等待放款；"loan_ok"放款成功) 
    //    /// </summary>
    //    [JsonProperty("loanInfo")]
    //    public LoanInfo LoanInfo { get; set; }

    //    [JsonProperty("orderStatus")]
    //    public string OrderStatus { get; set; }
    //    /// <summary>
    //    /// 买家全名
    //    /// </summary>
    //    [JsonProperty("buyerSignerFullname")]
    //    public string BuyerSignerFullname { get; set; }

    //    [JsonProperty("gmtPaySuccess")]
    //    public System.DateTimeOffset? GmtPaySuccess { get; set; }
    //    /// <summary>
    //    /// 放款状态
    //    /// </summary>
    //    [JsonProperty("loanStatus")]
    //    public string LoanStatus { get; set; }
    //    /// <summary>
    //    /// 资金状态
    //    /// </summary>
    //    [JsonProperty("fundStatus")]
    //    public string FundStatus { get; set; }



    //    [JsonProperty("oprLogDtoList")]
    //    public OprLogDtoList[] OprLogDtoList { get; set; }
    //}

    //public class OprLogDtoList
    //{

    //    [JsonProperty("id")]
    //    public string Id { get; set; }

    //    [JsonProperty("gmtModified")]
    //    public string GmtModified { get; set; }

    //    [JsonProperty("gmtCreate")]
    //    public string GmtCreate { get; set; }

    //    [JsonProperty("actionType")]
    //    public string ActionType { get; set; }

    //    [JsonProperty("childOrderId")]
    //    public object ChildOrderId { get; set; }

    //    [JsonProperty("operator")]
    //    public string Operator { get; set; }

    //    [JsonProperty("orderId")]
    //    public object OrderId { get; set; }

    //    [JsonProperty("memo")]
    //    public string Memo { get; set; }
    //}


    ///// <summary>
    ///// 子订单列表
    ///// </summary>
    //public class SonOrderList
    //{
    //    /// <summary>
    //    /// 贷款状况
    //    /// </summary>
    //    [JsonProperty("loanStatus")]
    //    public string LoanStatus { get; set; }

    //    [JsonProperty("affiliateCommission")]
    //    public PayAmount AffiliateCommission { get; set; }
    //    /// <summary>
    //    /// 中介费
    //    /// </summary>
    //    [JsonProperty("escrowFee")]
    //    public PayAmount EscrowFee { get; set; }

    //    [JsonProperty("childOrderId")]
    //    public object ChildOrderId { get; set; }
    //    /// <summary>
    //    /// 贷款额
    //    /// </summary>
    //    [JsonProperty("realLoanAmount")]
    //    public PayAmount RealLoanAmount { get; set; }

    //    [JsonProperty("waitLoanReson")]
    //    public string WaitLoanReson { get; set; }
    //}

    ///// <summary>
    ///// 物流信息
    ///// </summary>
    //public class LogisticInfoList
    //{
    //    /// <summary>
    //    /// "物流公司类型
    //    /// </summary>
    //    [JsonProperty("logisticsTypeCode")]
    //    public string LogisticsTypeCode { get; set; }
    //    /// <summary>
    //    /// 妥投时间
    //    /// </summary>
    //    [JsonProperty("gmtReceived")]
    //    public System.DateTimeOffset? GmtReceived { get; set; }
    //    /// <summary>
    //    /// 物流追踪号
    //    /// </summary>
    //    [JsonProperty("logisticsNo")]
    //    public string LogisticsNo { get; set; }
    //    /// <summary>
    //    /// 发货物流服务key
    //    /// </summary>
    //    [JsonProperty("logisticsServiceName")]
    //    public string LogisticsServiceName { get; set; }
    //    /// <summary>
    //    /// 发货时间
    //    /// </summary>
    //    [JsonProperty("gmtSend")]
    //    public System.DateTimeOffset? GmtSend { get; set; }
    //    /// <summary>
    //    /// 妥投状态 
    //    /// </summary>
    //    [JsonProperty("receiveStatus")]
    //    public string ReceiveStatus { get; set; }
    //    public override string ToString()
    //    {
    //        return string.Join(",", this.LogisticsTypeCode, this.LogisticsServiceName, this.LogisticsNo, this.GmtSend, this.ReceiveStatus + this.GmtReceived);
    //    }
    //}



















    //public class LoanInfo
    //{
    //}
}
