//// Generated by Xamasoft JSON Class Generator
//// http://www.xamasoft.com/json-class-generator

//using System;
//using System.Collections.Generic;
//using Newtonsoft.Json.Linq;
//using Newtonsoft.Json;

//namespace AliExpressSDK.RModel
//{
//    //public class TotalProductAmount
//    //{
//    //    public double amount { get; set; }
//    //    public int cent { get; set; }
//    //    public string currencyCode { get; set; }
//    //    public int centFactor { get; set; }
//    //    public Currency currency { get; set; }
//    //}



//    //public class ProductUnitPrice
//    //{
//    //    public double amount { get; set; }
//    //    public int cent { get; set; }
//    //    public string currencyCode { get; set; }
//    //    public int centFactor { get; set; }
//    //    public Currency currency { get; set; }
//    //}

//    //public class ProductList
//    //{
//    //    public int childId { get; set; }
//    //    public int goodsPrepareTime { get; set; }
//    //    public LogisticsAmount logisticsAmount { get; set; }
//    //    public string memo { get; set; }
//    //    public string sellerSignerFirstName { get; set; }
//    //    public TotalProductAmount totalProductAmount { get; set; }
//    //    public string freightCommitDay { get; set; }
//    //    public bool canSubmitIssue { get; set; }
//    //    public string productUnit { get; set; }
//    //    public string logisticsType { get; set; }
//    //    public string issueStatus { get; set; }
//    //    public int orderId { get; set; }
//    //    public string logisticsServiceName { get; set; }
//    //    public string sonOrderStatus { get; set; }
//    //    public string productSnapUrl { get; set; }
//    //    public bool moneyBack3x { get; set; }
//    //    public string sendGoodsTime { get; set; }
//    //    public string skuCode { get; set; }
//    //    public int productId { get; set; }
//    //    public int productCount { get; set; }
//    //    public string deliveryTime { get; set; }
//    //    public ProductUnitPrice productUnitPrice { get; set; }
//    //    public string sellerSignerLastName { get; set; }
//    //    public string productImgUrl { get; set; }
//    //    public string showStatus { get; set; }
//    //    public string productName { get; set; }
//    //}



//    //public class PayAmount
//    //{
//    //    public double amount { get; set; }
//    //    public int cent { get; set; }
//    //    public string currencyCode { get; set; }
//    //    public int centFactor { get; set; }
//    //    public Currency currency { get; set; }
//    //}

//    //public class OrderList
//    //{
//    //    public ProductList[] productList { get; set; }
//    //    public string issueStatus { get; set; }
//    //    public string frozenStatus { get; set; }
//    //    public string buyerLoginId { get; set; }
//    //    public string sellerSignerFullname { get; set; }
//    //    public bool hasRequestLoan { get; set; }
//    //    public int orderId { get; set; }
//    //    public PayAmount payAmount { get; set; }
//    //    public string gmtCreate { get; set; }
//    //    public string paymentType { get; set; }
//    //    public string orderStatus { get; set; }
//    //    public string buyerSignerFullname { get; set; }
//    //    public string gmtPayTime { get; set; }
//    //    public object timeoutLeftTime { get; set; }
//    //    public string fundStatus { get; set; }
//    //    public string gmtSendGoodsTime { get; set; }
//    //    public string bizType { get; set; }
//    //}

//    //public class ListResult
//    //{
//    //    [JsonProperty("orderId")]
//    //    public string OrderId { get; set; }
//    //}

//    //public class AliEvaluation:AliSuccessType
//    //{
//    //    [JsonProperty("listResult")]
//    //    public ListResult[] ListResult { get; set; }

//    //    [JsonProperty("totalItem")]
//    //    public int TotalItem { get; set; }
//    //}
//}

////namespace AliExpressData
////{

////    public class AliOrder
////    {
////        public int totalItem { get; set; }
////        public OrderList[] orderList { get; set; }
////    }

////}
