// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;


namespace SDK.Platform.AliExpressApi.RModel
{
    public class AeopAeProductSKU
    {
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("ipmSkuStock")]
        public int ipmSkuStock { get; set; }
        [JsonProperty("skuPrice")]
        public string SkuPrice { get; set; }

        [JsonProperty("skuStock")]
        public bool SkuStock { get; set; }

        [JsonProperty("aeopSKUProperty")]
        public AeopSKUProperty[] AeopSKUProperty { get; set; }

        [JsonProperty("skuCode")]
        public string SkuCode { get; set; }
    }

    public class AeopAeProductProperty
    {

        [JsonProperty("attrNameId")]
        public long AttrNameId { get; set; }
              [JsonProperty("attrValueId")]
        public long AttrValueId { get; set; }

        [JsonProperty("attrValue")]
        public string AttrValue { get; set; }

        [JsonProperty("attrName")]
        public string AttrName { get; set; }
    }
    public class AeopSKUProperty
    {
        public long propertyValueId;
        public long skuPropertyId;
        public string propertyValueDefinitionName;
        public string skuImage;
    }

    public class AliProductType : Model.AliSuccessType
    {
        [JsonProperty("summary")]
        public string Summary { get; set; }

        [JsonProperty("bulkOrder")]
        public int BulkOrder { get; set; }

        [JsonProperty("lotNum")]
        public int LotNum { get; set; }

        [JsonProperty("aeopAeProductSKUs")]
        public AeopAeProductSKU[] AeopAeProductSKUs { get; set; }

        [JsonProperty("detail")]
        public string Detail { get; set; }

        [JsonProperty("packageType")]
        public bool PackageType { get; set; }

        [JsonProperty("freightTemplateId")]
        public string FreightTemplateId { get; set; }

        [JsonProperty("subject")]
        public string Subject { get; set; }

        [JsonProperty("productMoreKeywords1")]
        public string ProductMoreKeywords1 { get; set; }

        [JsonProperty("productMoreKeywords2")]
        public string ProductMoreKeywords2 { get; set; }

        [JsonProperty("productUnit")]
        public int ProductUnit { get; set; }

        [JsonProperty("wsOfflineDate")]
        public string WsOfflineDate { get; set; }

        [JsonProperty("packageLength")]
        public int PackageLength { get; set; }

        [JsonProperty("wsDisplay")]
        public string WsDisplay { get; set; }

        [JsonProperty("isImageDynamic")]
        public bool IsImageDynamic { get; set; }

        [JsonProperty("packageHeight")]
        public int PackageHeight { get; set; }

        [JsonProperty("packageWidth")]
        public int PackageWidth { get; set; }

        [JsonProperty("isPackSell")]
        public bool IsPackSell { get; set; }

        [JsonProperty("isImageWatermark")]
        public bool IsImageWatermark { get; set; }

        [JsonProperty("ownerMemberSeq")]
        public int OwnerMemberSeq { get; set; }

        [JsonProperty("keyword")]
        public string Keyword { get; set; }

        [JsonProperty("categoryId")]
        public int CategoryId { get; set; }

        [JsonProperty("imageURLs")]
        public string ImageURLs { get; set; }

        [JsonProperty("productStatusType")]
        public string ProductStatusType { get; set; }

        [JsonProperty("ownerMemberId")]
        public string OwnerMemberId { get; set; }

        [JsonProperty("aeopAeProductPropertys")]
        public AeopAeProductProperty[] AeopAeProductPropertys { get; set; }

        [JsonProperty("productId")]
        public long ProductId { get; set; }

        [JsonProperty("grossWeight")]
        public string GrossWeight { get; set; }

        [JsonProperty("groupId")]
        public int GroupId { get; set; }

        [JsonProperty("deliveryTime")]
        public int DeliveryTime { get; set; }

        [JsonProperty("wsValidNum")]
        public int WsValidNum { get; set; }

        [JsonProperty("bulkDiscount")]
        public int BulkDiscount { get; set; }

        [JsonProperty("promiseTemplateId")]
        public int PromiseTemplateId { get; set; }

        [JsonProperty("productPrice")]
        public string ProductPrice { get; set; }
         [JsonProperty("src")]
        public string Src { get; set; }
         [JsonProperty("reduceStrategy")]
         public string ReduceStrategy { get; set; }
        //[JsonProperty("success")]
        //public bool Success { get; set; }
    }

}
